### ISSUE TITLE
Doesn't support "file:///" tabs

### ISSUE THREAD

**Issue by irvnriir** [tim-we/tabs-aside#110]
If that doesn't require more Permissions, i think it should work for such tabs as for any other .

**Comment by tim-we** [comment]
Unfortunately it is not possible: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create
> For security reasons, in Firefox, this may not be a privileged URL. So passing any of the following URLs will fail: [...]
> - file: URLs (i.e., files on the filesystem. However, to use a file packaged inside the extension, see below)

Just in case I wrote a small test extension to verify this:
[local_file_access_test-1.0.zip](https://github.com/tim-we/tabs-aside/files/6253495/local_file_access_test-1.0.zip)

I wish there was a special permission for this but right now there isn't. Let me know if I missed anything, otherwise please close this issue.
