### ISSUE TITLE
Support for contextual identities / multi-account containers

### ISSUE THREAD

**Issue by JordyScript** [tim-we/tabs-aside#22]
It would be nice if Tabs-aside had integration with contextual identities / Multi-Account containers.

There is some documentation on how to use the API here:
[MDN Guide for working with Contextual Identities](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Work_with_contextual_identities)

Features that would be nice to have:
-    Setting aside tabs should preserve their container information, such that restoring tabs makes them open in the same container they were saved from.
-    Another option would be to open an entire container or individual tabs inside of a specified container, overriding any original container information.
-    Also it would be nice if one had the feature to set aside only the tabs from a specified container.

As far as I am concerned we don't need any shortcuts for these functionalities since they are too complex to attach meaningful shortucts to.

**Comment by JordyScript** [comment]
The refactoring is definitely a priority and a necessity. I'm still learning and a bit too busy right now, but I would wanna help develop as well, cuz I really benefit from this functionality. A clean code base would be a huge help in that regard.

I like that you think about UI/UX in conjunction with functionality. I do think the idea should be refined a bit more though, because I see some problems with the idea you proposed as I understand it. Maybe we can think it through and discuss it some more. I will think it through, and then get back to you with some feedback.

**Comment by storyjesse** [comment]
I regularly brows using multiple containers so that I can login to sights with multiple users, eg. one tab is logged in as admin user, another as user and a third container views the page while not logged in at all.
Without these containers being preserved tabs aside is not useful to me. I currently have 512 tabs open at the moment because all my projects use multiple tabs and I don't have a workflow that allows me to set down one project and pick up another. I used to be able to do this with tab groups before tab containers came about and simplified my workflow a great deal, since it saved me logging off and back in as a different user.
Thanks heaps for your work. I'll keep looking for a solution since I don't have time to help with the code.

**Comment by tim-we** [comment]
I just skimmed through the MDN documentation regarding this and preserving the container seems pretty straight forward, just remember the `cookieStoreId`. This requires an additional optional permission "cookies".

This is probably the best and simplest way to implement this, but I would like to hear your opinion on this. One alternative would be a per-session approach instead of per-tab...

**Comment by tim-we** [comment]
Turns out this was really easy to implement, it will ship with v3. I am still looking for a reliable way to find the default `cookieStoreId` so that `csid=firefox-default` is not stored for every single tab.
Creating a new tab should work but that is a rather ugly solution... Any ideas?
