### ISSUE TITLE
support for reader view tabs

### ISSUE THREAD

**Issue by ingvar-lynn** [tim-we/tabs-aside#31]
reader view tabs has urls that look like this : "about:reader?url=https%3A%2F%2Fwww.ualberta.ca%2Fmedicine%2Fnews%2F2018%2Fjune%2Fputting-the-brakes-on-metastatic-cancer"

proposed fix:
https://github.com/tim-we/tabs-aside/blob/6ff096e69e4842c8a218fceff6099feb714daf50/util/common.js#L16
```
urlFilter: url => !(url.startsWith("about:") || url.startsWith("view-source:")) || url.startsWith("about:reader"),
```

**Comment by tim-we** [comment]
Hey thanks for your suggestion. The problem with your proposed fix is that `about:reader...` URLs are so called privileged URLs. Tabs like that can be set aside but not restored.
There is however support for this in the [official API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/create) by setting the `openInReaderMode` flag.
I will implement this in the upcoming version of Tabs Aside that I am currently working on.

**Comment by tim-we** [comment]
Reader view tabs will always be loaded when the tab is restored (it wont be affected by the tab loading setting).
This is due to API limitations since the `tabs.update` API does not allow toggling reader mode on or off. There is a specific `tabs.toggleReaderMode` API for this but that does not work when called while the tab is loading.
Therefore the user would have to wait twice as long (loading the page and then switching to reader mode which loads the page again...), which IMO is unacceptable.
