### ISSUE TITLE
Request: Editing sessions.

### ISSUE THREAD

**Issue by rayman89** [tim-we/tabs-aside#36]
Could you allow to:
1) remove tabs from inside a session individually or in bulk?
2) move the tabs inside of them to organize them also individually or in bulk?
3) change the order of the whole sessions?  For example lets say I have Music session Youtube session and  Games session on that order on the tab list. It would be nice to be able to change the order so for example Games is first then Music and Youtube at the end.

**Comment by tim-we** [comment]
1. You can already remove tabs individually from a session (right click menu). This does not work unfortunately if the session is active, that will change in the future. I can not promise bulk editing at this point since there is already quite a lot of stuff I need to do. I suggest you use Firefoxs bookmark manager for that.
2. Moving tabs per drag & drop is planned. Perhaps with v3 (currently working on that) or soon after that.
3. That is also planned. At the moment you could use the bookmark manager for that (Tabs aside just displays sessions in reverse order)

**Comment by rayman89** [comment]
Great I'll be looking forward to the updates then. Thank you.

**Comment by rayman89** [comment]
Sorry but I was wondering if there are there any news on the development of this feature or #16 . Thank you.

**Comment by tim-we** [comment]
I am sorry the development is currently so slow but I am currently working on my Bachelor thesis and that is a priority for me.
v3 is a complete rewrite of the extension in Typescript to make it more manageable and easier for other developers to participate. Unfortunately it is not quite done yet, and will still take some time.
I called the sections showing the tabs of a session in the sidebar `TabViews` [1].
Currently there is just the `SimpleList` which is (or rather will be) a slightly improved version of the current implementation (v2). With later releases I want to add more TabViews, including one that shows favicons next to the tabs and one that also shows thumbnails, similar to MS Edge. The easiest approach would be to just copy and modify `SimpleList.ts` and add the favicon code from [2]. I will do that for the v3 release and hopefully improve it later (things like favicon caching).

[1] https://github.com/tim-we/tabs-aside/tree/typescript/ts/sidebar/TabViews
[2] https://github.com/tim-we/tabs-aside/blob/typescript/ts/tab-loader/load.ts

**Comment by tim-we** [comment]
Tabs Aside 3 is released now and allows session editing (moving tabs between session, reordering) by moving the tabs from session window to window. It is currently not supported in the sidebar.
