### ISSUE TITLE
[Fixed] Make the sidebar not open with every new Firefox window

### ISSUE THREAD

**Issue by bruh0** [tim-we/tabs-aside#37]
![Gif](https://i.imgur.com/WjNUWmB.gif)

### How to recreate bug:
1. Open a new window, the sidebar opens.
2. Close the sidebar.
3. Repeat.

I see no option to disable this. Please correct me if I'm wrong.
This opens the "Tabs you've set aside" sidebar specifically. Disabling the extension fixes the problem.

**Edit:** Edited to be more specific

**Comment by tim-we** [comment]
I just tried this but this only happens when the sidebar is already open. This is the default behavior for extension sidebars. The extension could try to detect this and auto-close the sidebar again but this seems like an ugly hack.
I do agree there should be at least an option for this but in Firefox or a flag for extension developers to configure this behavior.
Perhaps you could file a bug at [bugzilla](https://bugzilla.mozilla.org/)?

**Comment by tim-we** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1475780

**Comment by tim-we** [comment]
There is actually nothing I can do here because:
- There is no API to close the sidebar on a specific window, `browser.sidebarAction.close()` seems to close the sidebar in the focused window
- Closing the sidebar is only allowed as a direct response to user input (limited to clicks on UI elements of the addon). You have to wait for the new window to open and after that closing the sidebar is not allowed anymore.

Please let me know if I missed something but AFAIK the only way to do this is to get FF to open up their API a bit...

**Comment by bruh0** [comment]
I made a gif showcasing the sidebar issue.
![Gif](https://i.imgur.com/WjNUWmB.gif)

Cheers.

**Comment by tim-we** [comment]
So the sidebar comes up every time you start Firefox? Can't reproduce that behavior. I guess it's a problem with your Firefox then. Just submit the bug to https://bugzilla.mozilla.org

**Comment by bruh0** [comment]
The problem seems to be resolved. It no longer happens in my browser. Cheers.
