### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by rayman89** [tim-we/tabs-aside#44]
When selecting the option "save tabs" sometimes the tabs dont get actually saved to the corresponding folder untill you "set them aside".   I lost more than 100 tabs this way =S. 

I also noticed that when you do that the addon does not recognize "discarded" tabs nor "lazy loaded" tabs.  So it only saves the current tab unless you have all the tabs on the window loaded which is not great. 

Hope you can fix this soon. Thank you.

**Comment by tim-we** [comment]
Thanks for sharing that and sorry for the inconvenience. Are you sure the tabs are not saved? I noticed that the sidebar does not always update and sometimes shows an old state (refreshing the sidebar is possible by closing it and opening it again, I recommend 2x Alt+Q)? 

Development of Tabs Aside 3 will continue in October. I do not have the time at the moment so I can't fix anything until October.
Tabs Aside 3 will have proper sidebar synchronization and the way "lazy loaded" tabs are handled is different because Firefox 63 will allow the creation of discarded tabs.

**Comment by rayman89** [comment]
What I did yesterday was selecting the "save tabs" option I saw the sidebar appear renamed that to "youtube" and closed the sidebar.  When I opened it again today to check something the "youtube" session was not there. I checked the bookmarks and there was no "youtube" folder either. I continued testing and noticed the other issues I mentioned.

**Comment by tim-we** [comment]
As this was related to Tabs Aside 2 and Tabs Aside 3 was completely rewritten from scratch I will close this issue now. Lets hope that never happens again...
