### ISSUE TITLE
Allow adding multiple tabs to existing session.

### ISSUE THREAD

**Issue by KaiPrince** [tim-we/tabs-aside#45]
Currently, the only way to add a tab to an existing section is to right-click the tab and select "add to existing section" from the 'tabs aside' menu.

However, this only allows you to perform this operation on one tab at a time.

There is a 'select tabs' menu under the 'more options' section of the main 'tabs aside' button (icon).
In this selection menu, there are options to "create a session", or "set aside".
 
Could you add another button for "add to existing session"?
This button would add all selected tabs to an existing session (which could be chosen from another menu in a similar manner as the current function).

**Comment by tim-we** [comment]
Yes, great idea, I can probably add this to Tabs aside version 3.1.  Another way to do this right now is of course using Firefox bookmark library.

**Comment by tim-we** [comment]
Sorry that it took so long but this feature will finally be included in the next release.
It works a little different now since Firefox has a new feature which allows you to select multiple tabs (Ctrl + Click). Right clicking a tab within that selection allows you to add all selected tabs to an existing session.
