### ISSUE TITLE
Feature Request: Save progress for YouTube videos

### ISSUE THREAD

**Issue by bruh0** [tim-we/tabs-aside#48]
When watching a YouTube video and selecting tabs aside, it saves the URL of the page. When recovering the tabs aside session only the URL is loaded, causing the page to load normally having the video to start from the beginning.

What I do about this is right click the video to copy the URL at current time, adding i.e. `&t=80` (time 1:20) to the copied URL and using this in place of the existing page URL to resume where I left off when loading the page back up.

Having the URL parameter `t` added automatically for `youtube.com/watch?v=` pages would be a great addition to the session saving.

There are other extensions that are made to keep track of video timestamps, but since this addon works with bookmarks, I believe it may be handy to have the timestamps saved into the actual bookmark's URL.

**Comment by tim-we** [comment]
Interesting idea but I do not think this will make it into the extension.

In this case the hard part is to get the current time of the video. I think you would have to insert a content script into the page which would have to be maintained and updated as it depends on YouTube's code.

I am sure this is possible but generally speaking I would like to avoid custom behavior for some selected websites because that would complicate things quite a bit and slow down development and reduce maintainability.

Perhaps this could be solved by a specialized companion extension? One could listen for bookmark changes, check if they are within the Tabs Aside folder structure and update the bookmarks (if they are for youtube.com) accordingly. I would also be happy to provide some sort of API for this.

If you are interested in developing such an extension please let me know, I'd be happy to help where I can as long as I do not have to do all the work. I hope that makes sense to you, or else let me know.
