### ISSUE TITLE
Feature Request: Right-Click Context Menu Option to Set Aside Tab to a new session

### ISSUE THREAD

**Issue by sahil48** [tim-we/tabs-aside#55]
Please add a right-click context menu option to set aside tabs to a new session. Currently, you can only add to existing sessions. **As of Firefox 64, it is now possible to select multiple tabs using ctrl-click and shift-click**. Please ensure that multiple tabs selected in this way can be set aside using the right-click context menu.

**Comment by tim-we** [comment]
This will be possible (and is already implemented, at least partially) with Tabs Aside 3 (currently in the works) but not via the tab context menu. Instead you can create sessions based on the selection from the browser action menu via the "select tabs" button (this currently broken in Tabs Aside 2).

Personally I prefer this solution since the menu API is not that great (AFAIK all you can do is a generic menu which is the same for all tabs). So unless there are any objections I would like to close this issue.

**Comment by woozalia** [comment]
How does one create a new session currently? The right-click menus only show existing sessions, and the main Tabs Aside panel doesn't seem to have an option for creating any. I must have done it somehow, earlier, because I now have 5 sessions (from early last year) -- but I don't remember how (it must have been intuitive) and I'm not seeing any way to do it now.

Also, is there a general user documentation page anywhere? I have more questions...

**Comment by tim-we** [comment]
![image](https://user-images.githubusercontent.com/10491533/73660867-55b3aa80-4699-11ea-9afe-dd90cb9b302e.png)
You can create a new session via the browser action menu (might be hidden in the >> panel) or the shortcut `Alt + Q`. This will create a session from all tabs within the current window. If you do not want to set the tabs aside you can choose the `Save tabs as session` option.

> Also, is there a general user documentation page anywhere? I have more questions...

There is none ATM, that is on my TODO list. If you want you can send me an email or create a new issue with a list of questions that should be answered in the (not yet existing) docs.

**Comment by tim-we** [comment]
This is implemented in the current version of Tabs Aside
