### ISSUE TITLE
Tab order is reversed in TA3 on restore

### ISSUE THREAD

**Issue by zargles** [tim-we/tabs-aside#64]
On restoring a session, the tabs are restored in the opposite order to the original order. This is not something that breaks the extension but is still irritating to me.

**Comment by tim-we** [comment]
Turns out a performance improvement I did a while ago was "too good"... The bookmarks were created so fast that upon creation the others did not exist yet resulting in every bookmark defaulting to index 0. 
Due to the insertion order this caused the reverse order effect. 
It is fixed now and live on AMO so just update your extensions and it should be fixed.
Thanks for submitting!
