### ISSUE TITLE
Bug?: Setting tabs aside after waking up from hibernating Windows computer

### ISSUE THREAD

**Issue by sahil48** [tim-we/tabs-aside#76]
When I wake my computer from hibernation in Windows 10, and set tabs aside, the tabs seem to open in a new window before being set aside. I'm not sure if this is because they were in another session. Additionally, sometimes NoScript detects this and highlights it as a potential cross-scripting script and the browser slows to a crawl or crashes.

When I started a new session of Firefox, the tabs set aside without opening other behaviors.

**Comment by tim-we** [comment]
When you set aside a window (that is not yet a session) that contains tabs that should not be set aside (pinned tabs if disabled and privileged URLs) Tabs Aside moves all "asidable" tabs to a new window first. This is done to share code with the "Save as session" functionality, which does the same except closing the tabs.

Also a new window is sometimes created to prevent the browser from closing when setting a session aside (when there are no other windows).

Otherwise this might be a bug, perhaps you could do some further testing? I am currently quite busy with uni, I'll have a look into the NoScript issue next week or so.

**Comment by sahil48** [comment]
Thanks.

I'll try to do some more testing when things settle down for me as well (might be a while, though).

> Also a new window is sometimes created to prevent the browser from closing when setting a session aside (when there are no other windows).

I first thought this, but then realized that I had 4 windows open. That's why I was puzzled. It is possible I had the Firefox addons page open, but other nonprivileged URLs had opened too in the window (80 or 90 tabs before firefox crashed).

**Comment by sahil48** [comment]
The only other addon I can think of causing these issues is total suspender. Maybe suspended tabs are treated as privaledged pages and get opened in a new window, and when they all get loaded at once, it stresses firefox.

**Comment by tim-we** [comment]
That is probably it. Currently only http(s) URLs are "asidable", extention pages (moz-extension://...) are not. I'll have try to fix this today or tomorrow.
